### ISSUE TITLE
last helm commit breaks helm-fuzzier

### ISSUE THREAD

**Issue by cremacs** [EphramPerdition/helm-fuzzier#12]
`C-x C-f` gives `Symbol's value as variable is void: helm-match-hash` and makes emacs unusable; helm-match-hash was removed in [this commit](https://github.com/emacs-helm/helm/commit/b1ec2d1ab48f137e71275153be9dd6ed21658122)

**Comment by Yevgnen** [comment]
same here

**Comment by EphramPerdition** [comment]
Thanks, I'm looking into it.

**Comment by EphramPerdition** [comment]
Pushed fix, tested ok in both pre and post change helm. 

Let me know if there are further issues.
