### ISSUE TITLE
what's the difference from `helm-flx`

### ISSUE THREAD

**Issue by bixuanzju** [EphramPerdition/helm-fuzzier#5]
So your package and `helm-flx` both provide fuzzy matching for `helm`, what is the difference between those two?

> For best results, use in conjunction with the 'helm-flx' package.

Do you mean we need to also install `helm-flx` and have both `(helm-flx-mode +1)` and `(helm-fuzzier-mode 1)` in our config?

Thanks!

**Comment by EphramPerdition** [comment]
> what is the difference between those two?

Each fixes a  different problem in Helm. You can read the notes in the source file for details.

> > For best results, use in conjunction with the 'helm-flx' package.
> 
> Do you mean we need to also install `helm-flx` and have both

yes.

**Comment by bixuanzju** [comment]
@EphramPerdition Thanks! I managed to find some explanation from history commit in README.

**Comment by EphramPerdition** [comment]
https://github.com/EphramPerdition/helm-fuzzier/blob/master/helm-fuzzier.el#L64
that and the next paragraph specifically explain that.
