### ISSUE TITLE
helm-locate-library breaking?

### ISSUE THREAD

**Issue by TheBB** [EphramPerdition/helm-fuzzier#9]
Can you reproduce this?

https://github.com/syl20bnr/spacemacs/issues/3747

**Comment by TheBB** [comment]
CC @nixmaniack

**Comment by EphramPerdition** [comment]
`helm-locate-library` works fine for me.

If you provide steps to repro with latest version, I'll look into it.

**Comment by EphramPerdition** [comment]
Closing, please reopen when you can provide repro steps.
